name: krew-index CI

on: [push]

jobs:

  build:
    name: Build and Tags
    runs-on: ubuntu-latest
    env: 
      KREW_VERSION: v0.3.3
      GO111MODULE: on

    steps:
    
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install kubectl
      run: |
        sudo curl -fsSL -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.13.1/bin/linux/amd64/kubectl
        sudo chmod +x /usr/bin/kubectl

    - name: Install krew (temporarily hardcode version)
      run: |
        cd "$(mktemp -d)" &&
        curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/download/${KREW_VERSION}/krew.{tar.gz,yaml}" &&
        tar zxvf krew.tar.gz &&
        ./krew-linux_amd64 install --manifest=krew.yaml --archive=krew.tar.gz
        
    - name: Get repository differences
      run: git diff --name-only --diff-filter=AM $TRAVIS_BRANCH...HEAD |
        grep -E 'plugins/.*' | tee /dev/stderr |
        xargs -I _ $HOME/bin/validate-krew-manifest -manifest _
